name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: master
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x86
      - uses: actions/checkout@v3
        with:
          repository: 'squeek502/win32-samples-rc-tests'
          submodules: true
          path: 'win32-samples-rc-tests'

      - run: zig version
      - run: zig env

      - name: Build
        run: |
          zig build
          Add-Content $env:GITHUB_PATH "$env:GITHUB_WORKSPACE\zig-out\bin"

      - name: Test
        run: zig build test
        
      - name: Win32 Samples
        working-directory: ./win32-samples-rc-tests
        run: |
          .\setup.ps1
          .\test.ps1 -ErrorOnAnyDiscrepancies -ErrorOnAnyLikelyPanics -IncludeWin32WillCompileErrorFiles -ExcludeLLVMRC -ExcludeWindres
